// app/javascript/v3/components/Form/Avatar.vue
<template>
  <div
    class="rounded-xl flex leading-[100%] font-medium items-center justify-center text-center cursor-default"
    :class="`h-[${size}px] w-[${size}]px ${colorClass}`"
    :style="style"
    aria-hidden="true"
  >
    <slot>{{ userInitial }}</slot>
  </div>
</template>

<script setup>
import { computed } from 'vue';

const colors = {
  1: 'bg-ash-200 text-ash-900',
  2: 'bg-amber-200 text-amber-900',
};

const props = defineProps({
  username: {
    type: String,
    default: '',
  },
  size: {
    type: Number,
    default: 72,
  },
});

const style = computed(() => ({
  fontSize: `${Math.floor(props.size / 2.5)}px`,
}));

const colorClass = computed(() => {
  return colors[(props.username.length % 2) + 1];
});

const userInitial = computed(() => {
  const parts = props.username.split(/[ -]/).filter(Boolean);
  let initials = parts.map(part => part[0].toUpperCase()).join('');
  return initials.slice(0, 2);
});
</script>

// crm/src/components/ui/avatar.tsx
import { cn } from '@/lib/utils'

export function Avatar({
  name,
  className,
}: {
  name: string
  className?: string
}) {
  const initials = name
    .split(' ')
    .slice(0, 2)
    .map((w) => w[0])
    .join('')
    .toUpperCase()

  const colors = [
    'bg-blue-100 text-blue-700',
    'bg-green-100 text-green-700',
    'bg-purple-100 text-purple-700',
    'bg-orange-100 text-orange-700',
    'bg-pink-100 text-pink-700',
  ]
  const color = colors[name.charCodeAt(0) % colors.length]

  return (
    <span
      className={cn(
        'inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-semibold',
        color,
        className,
      )}
    >
      {initials}
    </span>
  )
}
